spring:
  application:
    name: map
  datasource:
    url: jdbc:postgresql://localhost:5432/eugene
    username: mihail
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
geoapify:
  secret: ${GEOAPIFY_SECRET}
server:
  port: 8081